version: '3.3'
services:
   db:
      container_name: db
      build: ./postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: mbafiap2021
   mensageria:
      container_name: rabbitmq
      restart: always
      build: ./mensageria
      ports:
         - "5672:5672"
         - "15672:15672"
   nginx:
      build: ./nginx
      restart: always
      ports:
         - "80:80"
      depends_on:
         - myapp1
         - myapp2
         - myapp3
         - myapp4
   redis-one:
      container_name: redis-one
      restart: always
      build: ./redis-one
      ports:
      - "6379:6379"
   secundaryredis:
      container_name: secundaryredis
      restart: always
      build: ./secundaryredis
      ports:
      - "6380:6379"
   myapp1:
      container_name: myapp1
      build: ./myapp1
      ports:
        - "5001:9000"
      depends_on:
         - db
         - mensageria
         - redis-one
         - secundaryredis
      links:
         - db
         - mensageria
         - redis-one
         - secundaryredis
   myapp2:
      container_name: myapp2
      build: ./myapp2
      ports:
        - "5002:9000"
      depends_on:
         - db
         - mensageria
         - redis-one
         - secundaryredis
      links:
         - db
         - mensageria
         - redis-one
         - secundaryredis
   myapp3:
      container_name: myapp3
      build: ./myapp3
      ports:
        - "5003:9000"
      depends_on:
         - db
         - mensageria
         - redis-one
         - secundaryredis
      links:
         - db
         - mensageria
         - redis-one
         - secundaryredis
   myapp4:
      container_name: myapp4
      build: ./myapp4
      ports:
        - "5004:9000"
      depends_on:
         - db
         - mensageria
         - redis-one
         - secundaryredis
      links:
         - db
         - mensageria
         - redis-one
         - secundaryredis